load("@rules_cc//cc:defs.bzl", "cc_binary","cc_library")

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc","strBlob.h","strBlobPtr.h",
	    "strBlob.cpp","strBlobPtr.cpp","blob.h","BlobPtr.h",
	    "strVec.h","strVec.cpp","String.h","String.cpp","Allocator.h",
	    "vec.h","sharedPointer.h","pid.h","singleton.h","shared_pointer.h","unique_pointer.h",
	    "priorityQueue.h"]
)
